

title: Wooldridge Introductory Econometrics Python Solution By Ahmed H. Darwish
author: Ahmed H. Darwish
logo: Wooldridge Introductory Econometrics Python Solution By Ahmed H. Darwish
copytight: 2024

execute:
  execute_notebooks: "off"


latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib


repository:
  url: https://github.com/42Ahmed/woolpy
  path_to_book: docs  
  branch: master  

html:
  use_issues_button: true
  use_repository_button: true

include_toc: true

launch_buttons:
  colab_url: